# Base configs
baseurl: "https://nithin.info"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-158645866-1"

# UI configs
title: "Photography by Nithin Saripalli"
subtitle: "See the world through my eyes!"
author: "Nithin Saripalli"
header:
  title: "Photography"
  subtitle: "by Nithin Saripalli"
footer:
  name: "Hey there, my name is Nithin"
  bio: "I am a computer science major at Northeastern Major! I self-taught myself photography in 2016 and have been capturing the world through my lens ever sense."
  github: "You can find me <a href=\"https://github.com/nsaripalli/\">here!</a> ;)"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/nsaripalli"
  linkedin: "https://in.linkedin.com/in/nsaripalli"
  github: "https://www.github.com/nsaripalli"
